package DAO;
// Generated 02-dic-2015 22:22:59 by Hibernate Tools 4.3.1



/**
 * Normalvalue generated by hbm2java
 */
public class Normalvalue  implements java.io.Serializable {

    public Normalvalue(int id, Sensor sensor, int value) {
        this.id = id;
        this.sensor = sensor;
        this.value = value;
    }

     private int id;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Sensor getSensor() {
        return sensor;
    }

    public void setSensor(Sensor sensor) {
        this.sensor = sensor;
    }
     private Sensor sensor;
     private int value;

    public Normalvalue() {
    }


    public int getValue() {
        return this.value;
    }
    
    public void setValue(int value) {
        this.value = value;
    }




}


