package DAO;
// Generated 02-dic-2015 22:22:59 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Registry generated by hbm2java
 */
public class Registry  implements java.io.Serializable {


     private int id;
     private int idsensor;
     private int value;
     private Date date;

    public Registry() {
    }

    public Registry(int id, int idsensor, int value, Date date) {
       this.id = id;
       this.idsensor = idsensor;
       this.value = value;
       this.date = date;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getIdsensor() {
        return this.idsensor;
    }
    
    public void setIdsensor(int idsensor) {
        this.idsensor = idsensor;
    }
    public int getValue() {
        return this.value;
    }
    
    public void setValue(int value) {
        this.value = value;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


