package DAO;
// Generated 02-dic-2015 22:22:59 by Hibernate Tools 4.3.1


/**
 * Sensor generated by hbm2java
 */

public class Sensor implements java.io.Serializable {

    private int id;
    private String name;
    private Sensortype type;
    private String description;

    public Sensor() {
    }

    public Sensor(int id, String name, Sensortype type, String description) {
        this.id = id;
        this.name = name;
        this.type = type;
        this.description = description;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Sensortype getType() {
        return this.type;
    }

    public void setType(Sensortype type) {
        this.type = type;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}
