package DAO;
// Generated 02-dic-2015 22:22:59 by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private int id;
     private String user;
     private String password;
     private String description;

    public User() {
    }

	
    public User(int id, String user, String password) {
        this.id = id;
        this.user = user;
        this.password = password;
    }
    public User(int id, String user, String password, String description) {
       this.id = id;
       this.user = user;
       this.password = password;
       this.description = description;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


